import Footer from '@/components/layout/Footer.component';
import { PrimaryNavbar } from '@/components/layout/PrimaryNavbar.component';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<PrimaryNavbar />
				<main className='py-5'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
